### ISSUE TITLE
A new name for gen AI impact package

### ISSUE THREAD

**Issue by LucBERTON** [dataforgoodfr/12_genai_impact#6]
## Description

We need to find a fancy and easy to remember package name :)

## Solution

List and discuss package name ideas.

## Considerations

Should be easy to remember. 
Should be in line with Data for good values and ethical standards.

## Additional context

N/A

**Comment by LucBERTON** [comment]
Some package name ideas : 

### inspired by CodeCarbon
- AI Carbon 

### Play on words with "AI" or "Gen AI" or "GAI" 
- estim**AI**te
- evalu**AI**te
- sust**AI**n
- ret**AI**n
- adapt**AI**tion
- m**AI**te
- g**AI**nius (AI Genius)
- **GAI*teway
- **Gen**er**AI**te

### An Acronym
- GAIa (Gen AI Assessment) 
- G**AI**ME (Gen AI Impact Measurement and Evaluation)

**Comment by samuelrince** [comment]
A bit of clarification on this issue and some ideas. I found the name `genai_impact` to be very generic and self explanatory, but not very esthetic especilly as a python package. I think we can find a better name, probably shorter and fancier. 

I'll start with some ideas I have don't hesitate to comment or add yours! This list is ordered by preference.

- replug: because we kind of are replugging APIs to add a new layer that compute environmental impacts.

- greenfer: contraction of Green + Infer because we are focused on inference impacts.

- greenwrap: because we make wrappers for green ai.

- ecogen: contraction of Eco / Ecology + Generation / Generative

PS: @LucBERTON you beat me, I was writing my comment and yours was posted a minute ago.

**Comment by aqwvinh** [comment]
Thanks for the suggestions!
What about

- `greener`: inspired by @samuelrince 's `greenfer`
- `geneco`: `ecogen` is nice but it sounds smoother to me
- `pygenco`

**Comment by samuelrince** [comment]
Under discussion internally, thanks for the suggestions
